<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="admins-MacBook-Pro.local" name="com.shine.tests.Test_MidoutRegistration" tests="6" failures="1" timestamp="2020-03-15T14:43:34 IST" time="45.850" errors="0">
  <testcase name="upload_excel_file" time="2.095" classname="com.shine.tests.Test_MidoutRegistration"/>
  <system-out/>
  <testcase name="upload_html_file" time="3.356" classname="com.shine.tests.Test_MidoutRegistration"/>
  <system-out/>
  <testcase name="upload_jpg_image_file" time="2.695" classname="com.shine.tests.Test_MidoutRegistration"/>
  <system-out/>
  <testcase name="upload_file_without_extension" time="3.811" classname="com.shine.tests.Test_MidoutRegistration"/>
  <system-out/>
  <testcase name="test_registration_upload_resume_greater_than_5mb" time="6.787" classname="com.shine.tests.Test_MidoutRegistration"/>
  <system-out/>
  <testcase name="test_RegistrationUploadInvalidResume" time="27.106" classname="com.shine.tests.Test_MidoutRegistration">
    <failure type="java.lang.AssertionError" message="expected [Your name, email or phone number in resume must be same as in your profile.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Your name, email or phone number in resume must be same as in your profile.] but found []
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.shine.tests.Test_MidoutRegistration.checkErrorMessage(Test_MidoutRegistration.java:156)
at com.shine.tests.Test_MidoutRegistration.test_RegistrationUploadInvalidResume(Test_MidoutRegistration.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RegistrationUploadInvalidResume -->
  <system-out/>
</testsuite> <!-- com.shine.tests.Test_MidoutRegistration -->
