<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="admins-MacBook-Pro.local" name="com.shine.tests.Test_VwoScript" tests="7" failures="1" timestamp="2020-01-21T09:09:43 IST" time="230.036" errors="0">
  <testcase name="verify_vwo_tracking_code" time="1.392" classname="com.shine.tests.Test_VwoScript">
    <failure type="java.lang.AssertionError" message="can not find VWO script code did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: can not find VWO script code did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.shine.tests.Test_VwoScript.verify_vwo_tracking_code(Test_VwoScript.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_vwo_tracking_code -->
  <testcase name="verify_vwo_tracking_code_Jsrp" time="4.462" classname="com.shine.tests.Test_VwoScript"/>
  <testcase name="verify_vwo_tracking_Jsrp" time="35.217" classname="com.shine.tests.Test_VwoScript"/>
  <testcase name="verify_vwo_tracking_Jd" time="48.488" classname="com.shine.tests.Test_VwoScript"/>
  <testcase name="verify_loggedin_vwo_tracking_code" time="11.214" classname="com.shine.tests.Test_VwoScript"/>
  <testcase name="verify_loggedin_vwo_tracking_Jsrp" time="81.777" classname="com.shine.tests.Test_VwoScript"/>
  <testcase name="verify_loggedin_vwo_tracking_Jd" time="47.486" classname="com.shine.tests.Test_VwoScript"/>
</testsuite> <!-- com.shine.tests.Test_VwoScript -->
